pipeline {
  agent any

  stages {
    stage('Build') {

      steps {
        withMaven(maven : 'mavenWindows'){
          bat 'mvn clean test -Dmaven.test.failure.ignore=true'
        }
      }
    }
    stage('sonarqube') {

      steps {
        withMaven(maven : 'mavenWindows'){
          bat 'mvn sonar:sonar'
        }
      }
    }
    stage('Test') {

      steps {
        withMaven(maven : 'mavenWindows'){
          bat 'mvn clean test -Dmaven.test.failure.ignore=true'
        }
      }
    }


  }

}
