pipeline {
  agent any
  stages {
    stage('Build and Pacakge') {
      steps {
        withMaven(maven : 'mavenWindows'){
          bat 'mvn clean package -Dmaven.test.failure.ignore=true'
        }
      }
    }
    stage('Unit Test') {
      steps {
        withMaven(maven : 'mavenWindows'){
          bat 'mvn clean test -Dmaven.test.failure.ignore=true'
        }
      }
    }
    stage('sonarqube') {
      steps {
        withMaven(maven : 'mavenWindows'){
          bat 'mvn sonar:sonar'
        }
      }
    }
  }
}
